import { Box, Image } from "@chakra-ui/react";
import { Carousel } from "react-responsive-carousel";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import "./Slider.css";
function Slider() {
  function randomWord(words) {
    let randomNo = Math.floor(Math.random() * words.length);
    return words[randomNo];
  }
  let words = [
    "computer",
    "software",
    "coding",
    "programming",
    "Application",
    "Code",
    "Digital",
    "Engineer",
    "business",
    "work",
    "Engineering",
  ];
  return (
    <div>
      <Box p={2} >
        <Carousel
          infiniteLoop
          autoPlay
          interval={1000}
          showStatus={false}
          showArrows={false}
          showThumbs={false}
          className="slider"
        >
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
          <Box>
            <Image
              src={`https://source.unsplash.com/1024x1024/?${randomWord(words)}`}
            />
          </Box>
        </Carousel>
      </Box>
    </div>
  );
}

{
  /* <img src="https://source.unsplash.com/100x100/?computer" alt="" /> */
}
export default Slider;
